// Assemble the final gita.json from the verified _gita_assembled.json.
// Preserves curated seed metadata (explanations, daily_quote_eligible,
// holiday_tags) and adds a `source` block. Sanskrit from spine, English from
// Besant, transliteration from the proven transliterator (mechanical IAST).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { devanagariToIAST } from './translit.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, '..', 'assets', 'data');

const assembled = JSON.parse(readFileSync(join(__dirname, '_gita_assembled.json'), 'utf8'));
const current = JSON.parse(readFileSync(join(dataDir, 'gita.json'), 'utf8'));

// Preserve curated metadata from existing seed verses, keyed by id.
const seedMeta = new Map();
for (const v of current.verses) {
  seedMeta.set(v.id, {
    explanations: v.explanations ?? {},
    daily_quote_eligible: v.daily_quote_eligible ?? false,
    holiday_tags: v.holiday_tags ?? [],
  });
}

const SOURCE = {
  translator: 'Annie Besant',
  edition: 'The Bhagavad-Gîtâ (The Lord’s Song), 4th ed., 1922 (public domain)',
  sanskrit_source: 'GRETIL-derived Devanagari (gita/gita open dataset), cross-referenced with Besant 4th ed. parallel text',
  transliteration: 'Mechanical IAST generated by scripts/translit.mjs (rule-based, gated against seed)',
  verified: true,
};

function tidyEnglish(s) {
  return String(s)
    .replace(/\s+([.,;:!?’”])/g, '$1') // no space before punctuation (footnote-strip artifact)
    .replace(/\(\s*/g, '(')
    .replace(/\s+\)/g, ')')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

const verses = assembled
  .slice()
  .sort((a, b) => (a.chapter - b.chapter) || (a.verse - b.verse))
  .map((v) => {
    const id = `gita_${v.chapter}_${v.verse}`;
    const meta = seedMeta.get(id) ?? { explanations: {}, daily_quote_eligible: false, holiday_tags: [] };
    return {
      id,
      book: 'gita',
      chapter: v.chapter,
      chapter_name: v.chapter_name,
      verse: v.verse,
      sanskrit: v.sanskrit,
      transliteration: devanagariToIAST(v.sanskrit),
      translations: { english: tidyEnglish(v.english) },
      explanations: meta.explanations,
      daily_quote_eligible: meta.daily_quote_eligible,
      holiday_tags: meta.holiday_tags,
      source: SOURCE,
    };
  });

// Recompute chapter index counts from the actual assembled data.
const counts = new Map();
for (const v of verses) counts.set(v.chapter, (counts.get(v.chapter) ?? 0) + 1);
const chapters = current.chapters.map((c) => ({
  ...c,
  verse_count: counts.get(c.number) ?? c.verse_count,
}));

const total = verses.length;
const meta = {
  ...current.meta,
  total_verses: total,
};

const out = { meta, chapters, verses };
writeFileSync(join(dataDir, 'gita.json'), JSON.stringify(out, null, 2) + '\n');

// Validate by re-parsing.
JSON.parse(readFileSync(join(dataDir, 'gita.json'), 'utf8'));

console.log(`Wrote gita.json: ${total} verses across ${chapters.length} chapters.`);
console.log(`Chapter 13 verse_count: ${counts.get(13)} (recension variant; was 34).`);
console.log(`meta.total_verses: ${total}`);
const dqe = verses.filter((v) => v.daily_quote_eligible).length;
console.log(`daily_quote_eligible preserved: ${dqe}`);
const withExpl = verses.filter((v) => Object.keys(v.explanations).length > 0).length;
console.log(`verses with explanations: ${withExpl} (rest pending human-reviewed pass)`);
